const countries = [
                    
    { name: "Albania", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/2560px-Flag_of_Albania.svg.png" },
    { name: "Turkey", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/800px-Flag_of_Turkey.svg.png" },
    { name: "Turkey2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/800px-Flag_of_Turkey.svg.png" },
    { name: "Greece", image: "https://cdn.britannica.com/49/1049-004-AE4BAD3E/Flag-Greece.jpg" },
    { name: "Greece2", image: "https://cdn.britannica.com/49/1049-004-AE4BAD3E/Flag-Greece.jpg" },
    { name: "Bulgaria", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/1200px-Flag_of_Bulgaria.svg.png" },
    { name: "Macedonia", image: "https://cdn.britannica.com/08/6208-004-61460B40/Flag-North-Macedonia.jpg" },
    { name: "Kosovo", image: "https://cdn.britannica.com/18/114418-004-2A12F087/Flag-Kosovo.jpg" },
    { name: "Montenegro", image: "https://cdn.britannica.com/41/94841-004-BF5101EA/flag-Montenegro.jpg" },
    { name: "Serbia", image: "https://cdn.britannica.com/39/94839-004-EEB20F36/Flag-Serbia.jpg" },
    { name: "Romania", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/2560px-Flag_of_Romania.svg.png" },
    { name: "Bosnia", image: "https://cdn.britannica.com/02/6202-004-5E2B285D/Flag-Bosnia-and-Herzegovina.jpg" },
    { name: "Croatia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/2560px-Flag_of_Croatia.svg.png" },
    { name: "Croatia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/2560px-Flag_of_Croatia.svg.png" },
    { name: "Slovenia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/1200px-Flag_of_Slovenia.svg.png" },
    { name: "Hungary", image: "https://cdn.britannica.com/55/1455-004-5897143C/Flag-Hungary.jpg" },
    { name: "Slovakia", image: "https://cdn.britannica.com/88/7888-004-FD4BC606/Flag-Slovakia.jpg" },
    { name: "Austria", image: "https://www.nationalflags.shop/WebRoot/vilkasfi01/Shops/2014080403/53E6/2F4C/8E0D/6197/D4B9/0A28/100B/04F5/900px-Flag_of_Austria.svg.png" },
    { name: "Ukraine", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1200px-Flag_of_Ukraine.svg.png" },
    { name: "Moldova", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/2560px-Flag_of_Moldova.svg.png" },
    { name: "Belarus", image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Belarus.png" },
    { name: "Russia", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Kaliningrad", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia2", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia3", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia4", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia5", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia6", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia7", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    { name: "Russia8", image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png" },
    


    { name: "Finland", image: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg" },
    { name: "Sweden", image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1200px-Flag_of_Sweden.svg.png" },
    { name: "Norway", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/2560px-Flag_of_Norway.svg.png" },
    { name: "Norway2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/2560px-Flag_of_Norway.svg.png" },
    { name: "Norway3", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/2560px-Flag_of_Norway.svg.png" },
    { name: "Norway4", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/2560px-Flag_of_Norway.svg.png" },
    
    { name: "Estonia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/2560px-Flag_of_Estonia.svg.png" },
    { name: "Latvia", image: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg" },
    { name: "Lithuania", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/640px-Flag_of_Lithuania.svg.png" },
    { name: "Poland", image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1200px-Flag_of_Poland.svg.png" },
    { name: "Czechia", image: "https://cdn.britannica.com/86/7886-050-9D2D04BC/Flag-Czech-Republic.jpg" },
    { name: "Germany", image: "https://cdn.britannica.com/97/897-004-232BDF01/Flag-Germany.jpg" },
    { name: "Denmark", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/800px-Flag_of_Denmark.svg.png" },
    { name: "Denmark2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/800px-Flag_of_Denmark.svg.png" },
    { name: "Greenland", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/2560px-Flag_of_Greenland.svg.png" }, 
    { name: "Switzerland", image: "https://cdn.britannica.com/43/4543-004-C0D5C6F4/Flag-Switzerland.jpg" },
    { name: "Italy", image: "https://cdn.britannica.com/59/1759-004-F4175463/Flag-Italy.jpg" },
    { name: "Italy2", image: "https://cdn.britannica.com/59/1759-004-F4175463/Flag-Italy.jpg" },
    { name: "Italy3", image: "https://cdn.britannica.com/59/1759-004-F4175463/Flag-Italy.jpg" },
    { name: "France", image: "https://cdn.britannica.com/82/682-050-8AA3D6A6/Flag-France.jpg" },
    { name: "France2", image: "https://cdn.britannica.com/82/682-050-8AA3D6A6/Flag-France.jpg" },
    { name: "UnitedKingdom", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png" },
    { name: "UnitedKingdom2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png" },
    { name: "Ireland", image: "https://cdn.britannica.com/33/1733-004-5BA407D6/FLAG-Ireland.jpg" },
    { name: "Iceland", image: "https://cdn.britannica.com/85/1485-004-94C3DEDA/Flag-Iceland.jpg" },
    { name: "Belgium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/255px-Flag_of_Belgium_%28civil%29.svg.png" },
    { name: "Netherlands", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/2560px-Flag_of_the_Netherlands.svg.png" },
    { name: "Luxembourg", image: "https://cdn.britannica.com/23/2223-004-AE86DC5A/Flag-Luxembourg.jpg" },
    { name: "Spain", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },

    { name: "CanaryIslands", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },
    { name: "CanaryIslands2", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },
    { name: "CanaryIslands3", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },
    { name: "CanaryIslands4", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },
    { name: "CanaryIslands5", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },
    { name: "CanaryIslands6", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },
    { name: "CanaryIslands7", image: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg" },

    { name: "Portugal", image: "https://www.worldatlas.com/img/flag/pt-flag.jpg" },
    { name: "Cyprus", image: "https://cdn.britannica.com/83/7883-004-D09910C5/Flag-Cyprus.jpg" },
    { name: "Cyprus2", image: "https://cdn.britannica.com/83/7883-004-D09910C5/Flag-Cyprus.jpg" },
    { name: "Malta", image: "https://cdn.britannica.com/86/2286-004-51ACEA26/Flag-Malta.jpg" },
    { name: "Malta2", image: "https://cdn.britannica.com/86/2286-004-51ACEA26/Flag-Malta.jpg" },

    { name: "Morocco", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/2560px-Flag_of_Morocco.svg.png" },
    { name: "Algeria", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/1200px-Flag_of_Algeria.svg.png" },

    { name: "Tunisia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/225px-Flag_of_Tunisia.svg.png" },
    { name: "Libya", image: "https://cdn.britannica.com/37/3037-004-1C8F9958/Flag-Libya.jpg" },
    { name: "Egypt", image: "https://cdn.britannica.com/85/185-004-1EA59040/Flag-Egypt.jpg" },


    { name: "Eritrea", image: "https://cdn.britannica.com/09/09-004-63D8C33D/Flag-Eritrea.jpg" },
    { name: "Sudan", image: "https://cdn.britannica.com/96/4496-004-278A6211/Flag-Sudan.jpg" },
    { name: "Chad", image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg" },
    { name: "Niger", image: "https://www.worldatlas.com/img/flag/ne-flag.jpg" },
    { name: "Mali", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/1280px-Flag_of_Mali.svg.png" },
    { name: "Mauritania", image: "https://cdn.britannica.com/64/5064-004-FEF780F0/Flag-Mauritania.jpg" },
    { name: "WesternSahara", image: "https://upload.wikimedia.org/wikipedia/commons/7/76/Flag_of_Western_Sahara.png" },

 
    { name: "Djibouti", image: "https://cdn.britannica.com/06/06-004-29FFD888/Flag-Djibouti.jpg" },
    { name: "Somalia", image: "https://cdn.britannica.com/18/18-004-43399622/Flag-Somalia.jpg" },
    { name: "Ethiopia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/1024px-Flag_of_Ethiopia.svg.png" },
    { name: "SouthSudan", image: "https://cdn.britannica.com/37/150637-004-5D1F2321/Bandera-de-Sudan-del-Sur.jpg" },
    { name: "CentralAfricanRepublic", image: "https://cdn.britannica.com/80/7180-004-8AFA2B44/Flag-Central-African-Republic.jpg" },
    { name: "Cameroon", image: "https://cdn.britannica.com/42/5042-004-7FF4ACCA/Flag-Cameroon.jpg" },
    { name: "Nigeria", image: "https://cdn.britannica.com/68/5068-004-72A3F250/Flag-Nigeria.jpg" },
    { name: "Benin", image: "https://cdn.britannica.com/37/5037-004-E474738C/Flag-Benin.jpg" },
    { name: "BurkinaFaso", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/2560px-Flag_of_Burkina_Faso.svg.png" },
    { name: "Togo", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/1200px-Flag_of_Togo.svg.png" },
    { name: "Ghana", image: "https://cdn.britannica.com/54/5054-004-A09ABCDF/Flag-Ghana.jpg" },
    { name: "CotedIvoire", image: "https://cdn.britannica.com/48/5048-004-EA370A21/Flag-Cote-dIvoire.jpg" },
    { name: "Liberia", image: "https://cdn.britannica.com/60/5060-004-F0C9CBBF/Flag-Liberia.jpg" },
    { name: "SierraLeone", image: "https://cdn.britannica.com/72/5072-004-B35C4877/Flag-Sierra-Leone.jpg" },
    { name: "Guinea", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/2560px-Flag_of_Guinea.svg.png" },
    { name: "GuineaBissau", image: "https://cdn.britannica.com/58/5058-004-49C2D897/Flag-Guinea-Bissau.jpg" },
    { name: "CapeVerde", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde2", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde3", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde4", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde5", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde6", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde7", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde8", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },
    { name: "CapeVerde9", image: "https://cdn.britannica.com/44/5044-004-DEEC9E26/Flag-Cabo-Verde.jpg" },

    
    { name: "TheGambia", image: "https://cdn.britannica.com/52/5052-004-C6FC398B/Flag-of-The-Gambia.jpg" },

    { name: "Kenya", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/2560px-Flag_of_Kenya.svg.png" },
    { name: "Uganda", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/1280px-Flag_of_Uganda.svg.png" },
    { name: "Tanzania", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/2560px-Flag_of_Tanzania.svg.png" },
    { name: "Rwanda", image: "https://www.worldatlas.com/img/flag/rw-flag.jpg" },
    { name: "Burundi", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/2560px-Flag_of_Burundi.svg.png" },
    { name: "DRC", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/1024px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png" },
    { name: "Congo", image: "https://cdn.britannica.com/82/7182-004-2F057893/Flag-Republic-of-the-Congo.jpg" },
    { name: "Gabon", image: "https://cdn.britannica.com/85/7185-004-EBE5DBE5/Flag-Gabon.jpg" },
    { name: "SaoTomeAndPrincipe", image: "https://cdn.britannica.com/91/7191-004-76522C96/Flag-Sao-Tome-and-Principe.jpg" },
    { name: "SaoTomeAndPrincipe2", image: "https://cdn.britannica.com/91/7191-004-76522C96/Flag-Sao-Tome-and-Principe.jpg" },
    { name: "EquatorialGuinea", image: "https://cdn.britannica.com/50/5050-004-EB18953A/Flag-Equatorial-Guinea.jpg" },

    { name: "Mauritius", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/1024px-Flag_of_Mauritius.svg.png" },
    { name: "Mauritius2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/1024px-Flag_of_Mauritius.svg.png" },
    { name: "Seychelles", image: "https://cdn.britannica.com/93/4093-004-A9F95AC3/Flag-Seychelles.jpg" },
    { name: "Seychelles2", image: "https://cdn.britannica.com/93/4093-004-A9F95AC3/Flag-Seychelles.jpg" },
    { name: "Seychelles3", image: "https://cdn.britannica.com/93/4093-004-A9F95AC3/Flag-Seychelles.jpg" },
    { name: "Maldives", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/2560px-Flag_of_Maldives.svg.png" },
    { name: "Reunion", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "Madagascar", image: "https://cdn.britannica.com/46/2246-004-17A6E838/Flag-Madagascar.jpg" },
    { name: "Mayotte", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "Comoros", image: "https://cdn.britannica.com/40/7740-050-C43A463A/Flag-Comoros.jpg" },
    { name: "Comoros2", image: "https://cdn.britannica.com/40/7740-050-C43A463A/Flag-Comoros.jpg" },
    { name: "Comoros3", image: "https://cdn.britannica.com/40/7740-050-C43A463A/Flag-Comoros.jpg" },


    { name: "Mozambique", image: "https://cdn.britannica.com/23/4223-004-76407A84/Flag-Mozambique.jpg" },
    { name: "Malawi", image: "https://cdn.britannica.com/21/4221-004-93C8B4EC/Flag-Malawi.jpg" },
    { name: "Zambia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/1280px-Flag_of_Zambia.svg.png" },
    { name: "Angola", image: "https://www.worldatlas.com/r/w1200/img/flag/ao-flag.jpg" },
    { name: "Angola2", image: "https://www.worldatlas.com/r/w1200/img/flag/ao-flag.jpg" },

    { name: "Zimbabwe", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/1200px-Flag_of_Zimbabwe.svg.png" },
    { name: "Botswana", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/1280px-Flag_of_Botswana.svg.png" },
    { name: "Namibia", image: "https://cdn.britannica.com/25/4225-004-E2FF6664/Flag-Namibia.jpg" },
    { name: "Eswatini", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/800px-Flag_of_Eswatini.svg.png" },
    { name: "Lesotho", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/255px-Flag_of_Lesotho.svg.png" },
    { name: "SouthAfrica", image: "https://cdn.britannica.com/27/4227-004-32423B42/Flag-South-Africa.jpg" },

    { name: "Israel", image: "https://cdn.britannica.com/53/1753-004-03582EDA/Flag-Israel.jpg" },
    { name: "Palestine", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/2560px-Flag_of_Palestine.svg.png" },
    { name: "Jordan", image: "https://cdn.britannica.com/40/1840-004-718BA773/Flag-Jordan.jpg" },
    { name: "Lebanon", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/2560px-Flag_of_Lebanon.svg.png" },
    { name: "Syria", image: "https://cdn.britannica.com/50/4550-004-7B368E09/Flag-Syria.jpg" },
    { name: "Iraq", image: "https://cdn.britannica.com/28/1728-004-EBF4B6FF/Flag-Iraq.jpg" },
    { name: "SaudiArabia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/2000px-Flag_of_Saudi_Arabia.svg.png" },
    { name: "Yemen", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/1280px-Flag_of_Yemen.svg.png" },
    { name: "Oman", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/2000px-Flag_of_Oman.svg.png" },
    { name: "Oman2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/2000px-Flag_of_Oman.svg.png" },
    { name: "UAE", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/255px-Flag_of_the_United_Arab_Emirates.svg.png" },
    { name: "Qatar", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_Qatar_%283-2%29.svg/1200px-Flag_of_Qatar_%283-2%29.svg.png" },
    { name: "Bahrain", image: "https://cdn.britannica.com/67/5767-004-E0FF7201/Flag-Bahrain.jpg" },
    { name: "Kuwait", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/1200px-Flag_of_Kuwait.svg.png" },
    { name: "Iran", image: "https://cdn.britannica.com/22/1722-004-EAD033D8/Flag-Iran.jpg" },


    { name: "Azerbaijan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1200px-Flag_of_Azerbaijan.svg.png" },
    { name: "Azerbaijan2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1200px-Flag_of_Azerbaijan.svg.png" },
    { name: "Armenia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/1200px-Flag_of_Armenia.svg.png" },
    { name: "Georgia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/255px-Flag_of_Georgia.svg.png" },

    { name: "Kazakhstan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_Kazakhstan_%283-2%29.svg/2560px-Flag_of_Kazakhstan_%283-2%29.svg.png" },
    { name: "Uzbekistan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Uzbekistan_%283-2%29.svg/1280px-Flag_of_Uzbekistan_%283-2%29.svg.png" },
    { name: "Kyrgyzstan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/800px-Flag_of_Kyrgyzstan.svg.png?20230107130638" },
    { name: "Turkmenistan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/2560px-Flag_of_Turkmenistan.svg.png" },
    { name: "Tajikistan", image: "https://www.youngpioneertours.com/wp-content/uploads/2020/04/Flag_of_Tajikistan-600x300.png" },
    { name: "Afghanistan", image: "https://cdn.britannica.com/40/5340-004-B25ED5CF/Flag-Afghanistan.jpg" },
    { name: "Pakistan", image: "https://cdn.britannica.com/46/3346-004-D3BDE016/flag-symbolism-Pakistan-design-Islamic.jpg" },

    { name: "India", image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/1200px-Flag_of_India.svg.png" },
    { name: "Nepal", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/1200px-Flag_of_Nepal.svg.png" },
    { name: "Bhutan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/1280px-Flag_of_Bhutan.svg.png" },
    { name: "Bangladesh", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/1200px-Flag_of_Bangladesh.svg.png" },
    { name: "SriLanka", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/1280px-Flag_of_Sri_Lanka.svg.png" },


    { name: "Myanmar", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/1200px-Flag_of_Myanmar.svg.png" },
    { name: "Thailand", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/640px-Flag_of_Thailand.svg.png" },
    { name: "Laos", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/2560px-Flag_of_Laos.svg.png" },
    { name: "Cambodia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/2560px-Flag_of_Cambodia.svg.png" },
    { name: "Vietnam", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/2560px-Flag_of_Vietnam.svg.png" },

    { name: "Malaysia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/2560px-Flag_of_Malaysia.svg.png" },
    { name: "Malaysia2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/2560px-Flag_of_Malaysia.svg.png" },
    { name: "Brunei", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/2560px-Flag_of_Brunei.svg.png" },

    { name: "Indonesia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia3", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia4", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia5", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia6", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia7", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia8", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia9", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia10", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia12", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },
    { name: "Indonesia13", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png?20200822164827" },


    { name: "Philippines", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },
    { name: "Philippines2", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },
    { name: "Philippines3", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },
    { name: "Philippines4", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },
    { name: "Philippines5", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },
    { name: "Philippines6", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },
    { name: "Philippines7", image: "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg" },

    { name: "PapuaNewGuinea", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/800px-Flag_of_Papua_New_Guinea.svg.png" },
    { name: "PapuaNewGuinea2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/800px-Flag_of_Papua_New_Guinea.svg.png" },
    { name: "PapuaNewGuinea3", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/800px-Flag_of_Papua_New_Guinea.svg.png" },
    { name: "PapuaNewGuinea4", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/800px-Flag_of_Papua_New_Guinea.svg.png" },

    { name: "China", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1280px-Flag_of_the_People%27s_Republic_of_China.svg.png" },
    { name: "China2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1280px-Flag_of_the_People%27s_Republic_of_China.svg.png" },
    { name: "Mongolia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/2560px-Flag_of_Mongolia.svg.png" },
    { name: "Taiwan", image: "https://cdn.britannica.com/62/4562-004-C04E54C5/Flag-Taiwan.jpg" },
    { name: "NorthKorea", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/1600px-Flag_of_North_Korea.svg.png" },
    { name: "SouthKorea", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1280px-Flag_of_South_Korea.svg.png" },


    { name: "Japan", image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1200px-Flag_of_Japan.svg.png" },
    { name: "Japan2", image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1200px-Flag_of_Japan.svg.png" },
    { name: "Japan3", image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1200px-Flag_of_Japan.svg.png" },


    { name: "TimorLeste", image: "https://cdn.britannica.com/60/72760-050-4F87197C/Flag-of-East-Timor.jpg" },

    { name: "SolomonIslands2", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands3", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands4", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands5", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands6", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands7", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands8", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands9", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands10", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands11", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands12", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands13", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands14", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands15", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands16", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands17", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands18", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands19", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands20", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands21", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands22", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands23", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands24", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands25", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands26", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands27", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands28", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands29", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands30", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands31", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands32", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },
    { name: "SolomonIslands33", image: "https://cdn.britannica.com/98/3298-004-5CE240EE/Flag-Solomon-Islands.jpg" },

    { name: "Australia", image: "https://cdn.britannica.com/78/6078-004-77AF7322/Flag-Australia.jpg" },
    { name: "Australia2", image: "https://cdn.britannica.com/78/6078-004-77AF7322/Flag-Australia.jpg" },

    { name: "NewZealand", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/800px-Flag_of_New_Zealand.svg.png" },
    { name: "NewZealand2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/800px-Flag_of_New_Zealand.svg.png" },

    { name: "NewCaledonia", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia2", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia3", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia4", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia5", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia6", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia7", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    { name: "NewCaledonia8", image: "https://www.flagsonline.it/uploads/2019-11-13/1200-0/Nouvelle-caledonie_Drapeau_Flag_Bandiera.jpg" },
    
    // { name: "Vanuatu1", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu2", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vaunatu3", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu4", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu5", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu6", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu7", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu8", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu9", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu10", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu11", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu12", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu13", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu14", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu15", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu16", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu17", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    // { name: "Vanuatu18", image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg" },
    
    { name: "Canada10", image: "https://cdn.britannica.com/68/7068-004-7848FEB4/Flag-Canada.jpg" },
    { name: "Main-USA", image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1200px-Flag_of_the_United_States.svg.png" },
    { name: "Mexico", image: "https://cdn.britannica.com/73/2573-004-29818847/Flag-Mexico.jpg" },
    { name: "Guatemala", image: "https://cdn.britannica.com/13/7213-004-FFC58C1D/Flag-Guatemala.jpg" },
    { name: "Belize", image: "https://cdn.britannica.com/07/7207-004-A82842C0/Flag-Belize.jpg" },
    { name: "ElSalvador", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/2560px-Flag_of_El_Salvador.svg.png" },
    { name: "Honduras", image: "https://cdn.britannica.com/16/7216-004-F1400CA0/Flag-Honduras.jpg" },
    { name: "Nicaragua", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/1280px-Flag_of_Nicaragua.svg.png" },
    { name: "CostaRica", image: "https://cdn.britannica.com/25/7225-004-65F33B16/Flag-Costa-Rica.jpg" },
    { name: "Panama", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/1200px-Flag_of_Panama.svg.png" },

    { name: "Columbia", image: "https://cdn.britannica.com/68/7668-004-08492AB7/Flag-Colombia.jpg" },
    { name: "Venezuela", image: "https://cdn.britannica.com/04/4904-004-EBEFDE35/Flag-Venezuela.jpg" },
    { name: "Guyana", image: "https://cdn.britannica.com/06/1106-004-F6772F48/Flag-Guyana.jpg" },
    { name: "Suriname", image: "https://cdn.britannica.com/20/4520-004-F090B3C8/Flag-Suriname.jpg" },
    { name: "FrenchGuiana", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "Brazil", image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/640px-Flag_of_Brazil.svg.png" },
    { name: "Ecuador", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1440px-Flag_of_Ecuador.svg.png" },
    { name: "Peru", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Peru_%28state%29.svg/2560px-Flag_of_Peru_%28state%29.svg.png" },
    { name: "Bolivia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Bolivia_%28state%29.svg/2560px-Flag_of_Bolivia_%28state%29.svg.png" },
    { name: "Paraguay", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/1024px-Flag_of_Paraguay.svg.png" },
    { name: "Argentina", image: "https://cdn.britannica.com/69/5869-004-7D75CD05/Flag-Argentina.jpg" },
    { name: "Argentina2", image: "https://cdn.britannica.com/69/5869-004-7D75CD05/Flag-Argentina.jpg" },
    { name: "Chile", image: "https://cdn.britannica.com/85/7485-004-00B07230/Flag-Chile.jpg" },
    { name: "Chile2", image: "https://cdn.britannica.com/85/7485-004-00B07230/Flag-Chile.jpg" },
    { name: "Uruguay", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/2560px-Flag_of_Uruguay.svg.png" },


    
    { name: "Bahamas", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas2", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas3", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas4", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas5", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas6", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas7", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas8", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas9", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas10", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas11", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas12", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas13", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas14", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas15", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas16", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas17", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "Bahamas18", image: "https://cdn.britannica.com/06/5106-004-B8EE9FD3/Flag-of-The-Bahamas.jpg"},
    { name: "TurksAndCaicos", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/800px-Flag_of_the_Turks_and_Caicos_Islands.svg.png?20190222024420" },
    { name: "TurksAndCaicos2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/800px-Flag_of_the_Turks_and_Caicos_Islands.svg.png?20190222024420" },
    { name: "TurksAndCaicos3", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/800px-Flag_of_the_Turks_and_Caicos_Islands.svg.png?20190222024420" },
    { name: "Cuba", image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg" },
    { name: "CaymanIslands", image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg" },
    { name: "CaymanIslands2", image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg" },
    { name: "CaymanIslands3", image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg" },
    { name: "Jamaica", image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg" },
    { name: "Haiti", image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg" },
    { name: "DominicanRepublic", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/800px-Flag_of_the_Dominican_Republic.svg.png?20221206230445" },
    { name: "PuertoRico", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/2560px-Flag_of_Puerto_Rico.svg.png" },
    { name: "PuertoRico2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/2560px-Flag_of_Puerto_Rico.svg.png" },
    { name: "PuertoRico3", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/2560px-Flag_of_Puerto_Rico.svg.png" },
    { name: "BritishVirginIslands", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/2560px-Flag_of_the_British_Virgin_Islands.svg.png" },
    { name: "UnitedStatesVirginIslands", image: "https://cdn.britannica.com/66/69566-004-9AB80929/Flag-US-Virgin-Islands.jpg" },
    { name: "UnitedStatesVirginIslands2", image: "https://cdn.britannica.com/66/69566-004-9AB80929/Flag-US-Virgin-Islands.jpg" },
    { name: "UnitedStatesVirginIslands3", image: "https://cdn.britannica.com/66/69566-004-9AB80929/Flag-US-Virgin-Islands.jpg" },
    { name: "Anguilla", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/1200px-Flag_of_Anguilla.svg.png" },
    { name: "SaintMartin", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "SaintBarthelemy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Saint_Barthélemy_%28local%29.svg/2560px-Flag_of_Saint_Barthélemy_%28local%29.svg.png" },
    { name: "SintMaarten", image: "https://cdn.britannica.com/97/145497-004-21670742/Flag-Sint-Maarten.jpg" },
    { name: "SaintKittsAndNevis", image: "https://cdn.britannica.com/22/5122-004-89773429/Flag-Saint-Kitts-and-Nevis.jpg" },
    { name: "SaintKittsAndNevis2", image: "https://cdn.britannica.com/22/5122-004-89773429/Flag-Saint-Kitts-and-Nevis.jpg" },
    { name: "AntiguaAndBarbuda", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/1200px-Flag_of_Antigua_and_Barbuda.svg.png" },
    { name: "AntiguaAndBarbuda2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/1200px-Flag_of_Antigua_and_Barbuda.svg.png" },
    { name: "Montserrat", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/1200px-Flag_of_Montserrat.svg.png" },
    { name: "Guadeloupe", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "Guadeloupe2", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "Guadeloupe3", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },

    { name: "Dominica", image: "https://cdn.britannica.com/12/5112-004-58893CEE/Flag-Dominica.jpg" },
    { name: "Martinique", image: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg" },
    { name: "SaintLucia", image: "https://cdn.britannica.com/24/5124-050-8F6BCAC8/Flag-Saint-Lucia.jpg" },
    { name: "SaintVincentAndTheGrenadines", image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg" },
    { name: "Barbados", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/1500px-Flag_of_Barbados.svg.png" },
    { name: "Grenada", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/1200px-Flag_of_Grenada.svg.png" },
    { name: "TrinidadAndTobago", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/2560px-Flag_of_Trinidad_and_Tobago.svg.png" },
    { name: "Aruba", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/1200px-Flag_of_Aruba.svg.png" },
    { name: "Curacao", image: "https://cdn.britannica.com/96/145496-004-62DE1CB9/Flag-Curacao.jpg" },
    { name: "CaribbeanNetherlands", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/2560px-Flag_of_the_Netherlands.svg.png" },


    

    

    { name: "Palau", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/2560px-Flag_of_Palau.svg.png" },
    
    { name: "Micronesia", image: "https://cdn.britannica.com/92/3292-004-831A447B/Flag-Federated-States-of-Micronesia.jpg" },
    { name: "Micronesia2", image: "https://cdn.britannica.com/92/3292-004-831A447B/Flag-Federated-States-of-Micronesia.jpg" },
    { name: "Micronesia3", image: "https://cdn.britannica.com/92/3292-004-831A447B/Flag-Federated-States-of-Micronesia.jpg" },
    { name: "Nauru", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/1280px-Flag_of_Nauru.svg.png" },
    { name: "Tuvalu", image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg" }


    // { name: "Austria", image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1200px-Flag_of_Poland.svg.png" },

    
];

for (let i = 0; i < countries.length; i++) {
  let country = countries[i];
  document.querySelector("#" + country.name).addEventListener("click", function() {
    let imageDisplay = document.querySelector("#image-display");
    imageDisplay.style.display = "block";
    imageDisplay.innerHTML = `<img style="width: 70px; height: 50px;" src="${country.image}" alt="${country.name}">`;
  });
}